{
    'name': 'Gate Pass Management',
    'version': '18.0.1.0',
    'summary': 'Manage vehicle and visitor gate passes with approval workflow',
    'category': 'Agro Modules',
    'author': 'Nadim Hossain',
    'website': 'https://betopiagroup.com/',
    'depends': ['base', 'mail', 'sale', 'stock', 'web', 'hr', 'purchase', 'agro_core'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/gatepass_sequence.xml',
        'views/config_views.xml',
        'views/gatepass_people_views.xml',
        'views/gatepass_views.xml',
        'views/res_users_views.xml',
        'views/gatepass_menus.xml',
        'wizard/gatepass_approval.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}